package com.damiankoziel.forum.commons;

public enum Category {
    CELEBRITY, ANIMAL, PEOPLE, CURIOSITY, SCIENCE, FUNNY, NATURE, INTERESTING_PLACE, ART, MOVIE, FASHION, SALE,
    MUSIC, CULTURE, SPORT, WARSZAWA, LUBLIN, POZNAN, KIELCE, KATOWICE, GDANSK, GDYNIA, KRAKOW, WROCLAW
}
